-- VHDL Entity MIPS.MIPS_tester.interface
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

ENTITY MIPS_tester IS
   PORT ( 
		clock								: out 	STD_LOGIC; 
		PC									: in  STD_LOGIC_VECTOR( 9 DOWNTO 0 );
     	Instruction_out						: in 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		LED						 			: in 	STD_LOGIC_VECTOR( 7 DOWNTO 0 );
		HEX0, HEX1, HEX2, HEX3, HEX4, HEX5 	: in 	STD_LOGIC_VECTOR( 6 DOWNTO 0 );
		SW 									: out 	STD_LOGIC_VECTOR( 7 DOWNTO 0 );
		push0, push1, push2, push3 			: out 	STD_LOGIC;
		PWM									: in   STD_LOGIC);

-- Declarations

END MIPS_tester ;

--
-- VHDL Architecture MIPS.MIPS_tester.struct
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;


ARCHITECTURE struct OF MIPS_tester IS

   -- Architecture declarations

   -- Internal signal declarations


   -- ModuleWare signal declarations(v1.9) for instance 'U_0' of 'clk'
   SIGNAL mw_U_0clk : std_logic;
   SIGNAL mw_U_0disable_clk : boolean := FALSE;

   -- ModuleWare signal declarations(v1.9) for instance 'U_1' of 'pulse'
   SIGNAL mw_U_1pulse, mw_U_2pulse, mw_U_3pulse, mw_U_4pulse : std_logic :='0';


BEGIN
	
   -- ModuleWare code(v1.9) for instance 'U_0' of 'clk'
   u_0clk_proc: PROCESS
   BEGIN
      WHILE NOT mw_U_0disable_clk LOOP
         mw_U_0clk <= '0', '1' AFTER 50 ns;
         WAIT FOR 100 ns;
      END LOOP;
      WAIT;
   END PROCESS u_0clk_proc;
   mw_U_0disable_clk <= TRUE AFTER 1000000000 ns;
   clock <= mw_U_0clk;

   -- ModuleWare code(v1.9) for instance 'U_1' of 'pulse'
   -- reset <= mw_U_1pulse;
   -- u_1pulse_proc: PROCESS
   -- BEGIN
      -- mw_U_1pulse <= 
         -- '0',
         -- '1' AFTER 20 ns,
         -- '0' AFTER 120 ns;
      -- WAIT;
    -- END PROCESS u_1pulse_proc;
	
	-- p1 : process
	-- begin
		-- PC_EN <= '0',
				-- '1' after 50000 ns;
		-- WAIT;
	-- END PROCESS p1;
	--PC_EN <= '1';
   
   u_1pulse_proc: PROCESS
   BEGIN
      mw_U_1pulse <= 
         '0',
         '1' AFTER 20 ns,
		 -- '0' AFTER 120 ns;
         '0' AFTER 120 ns;
      WAIT;
    END PROCESS u_1pulse_proc;
	push0 <= not(mw_U_1pulse);
	
	
	key1pulse_proc: PROCESS
   BEGIN
      mw_U_2pulse <= 
         '0',
         '1' AFTER 35000 ns,
         '0' AFTER 36000 ns;
		 --'1' AFTER 47000 ns,
		 --'0' AFTER 48000 ns;
      WAIT;
    END PROCESS key1pulse_proc;
	push1 <= not(mw_U_2pulse);
	
	sw_proc: PROCESS
   BEGIN
      SW <= "00000000",
			"10100000" AFTER 35000 ns,
			"00000111" AFTER 37000 ns;
      WAIT;
    END PROCESS sw_proc;
	
	
	key2pulse_proc: PROCESS
   BEGIN
      mw_U_3pulse <= 
         '0',
         '1' AFTER 40000 ns,
         '0' AFTER 41000 ns;
		 --'1' AFTER 100000 ns,
		 --'0' AFTER 101000 ns;
      WAIT;
    END PROCESS key2pulse_proc;
	--push2 <= not(mw_U_3pulse);
--	
	key3pulse_proc: PROCESS
   BEGIN
      mw_U_4pulse <= 
         '0',
--         '1' AFTER 43000 ns,
--         '0' AFTER 44000 ns,
		 '1' AFTER 130000 ns,
		 '0' AFTER 131000 ns;
      WAIT;
    END PROCESS key3pulse_proc;
	push3 <= not(mw_U_4pulse);
	

   -- Instance port mappings.

END struct;
